version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ejb_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ejbdb
      MYSQL_USER: ejbuser
      MYSQL_PASSWORD: ejbpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
